[spruce] Bump @pinecone-database version to support global control plane
pinecone-io/recommender-example-typescript pull request #4
Opened 2023-12-20 19:14 UTC by austin-denoble

## Problem
We've been working to support the new global control plane service in the Pinecone clients. We need to update our sample apps to migrate to the new client versions, and update associated code paths as needed.

## Solution
- Update `README.md`, `.env.example`, and `validateEnvironmentVariables()` to remove `PINECONE_ENVIRONMENT`.
- Update `index.ts` to handle the new `listIndexes()` response shape, and passing the proper config to `createIndex()`. Update relevant snippets in `README.md`.

I also took a pass at some minor cleanup not directly related to the upgrade:
- Ran prettier across the codebase, some stuff was oddly formatted.
- Using `validateEnvironmentVariables()` relevant code is run (`index.ts`, and `recommend.ts`). This is minor as `getEnv()` will throw in the same way, but the validation util wasn't used at all.
- Removed duplicate `sliceIntoChunks()` function.
- Fixed an apparent issue in `chunkedUpsert()` where `chunks.map(async (chunk) => ...)` was upserting `vectors` and not the specific `chunk`.

For now, I've created a spruce branch to merge this into as we probably don't want to release sample apps that aren't aligned with what's available publicly.

## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

## Test Plan
There are no unit tests associated with this project, so testing manually is required. I tested both the embedding and upsert path along with the recommendations path, and they seem to work as we'd expect. We should add some level of testing and validation to this app at some point.

### Validate embedding and upsert
`npm run index`
![Screenshot 2023-12-20 at 2 13 24 PM](https://github.com/pinecone-io/recommender-example-typescript/assets/119623786/944bca97-7b8f-42a9-8f04-df75a45a7c94)

### Validate recommendations
`npm run recommend -- --query="Xbox" --section="Games
![Screenshot 2023-12-20 at 2 14 04 PM](https://github.com/pinecone-io/recommender-example-typescript/assets/119623786/01fd23a8-4ce6-4acc-8ce5-bda9f7fc29b5)
"`

2023-12-20 19:15 UTC, austin-denoble commented on src/index.ts
> +validateEnvironmentVariables();
Added validation here.

2023-12-20 19:15 UTC, austin-denoble commented on src/index.ts
> +  if (!indexList.indexes?.some((index) => index.name === indexName)) {
Update to handle `listIndexes()` response and the `createIndex()` call below now includes `spec`.

2023-12-20 19:16 UTC, austin-denoble commented on src/recommend.ts
> +    throw new Error(
Lint was complaining about not throwing an `Error` here.

2023-12-20 19:16 UTC, austin-denoble commented on src/utils/chunkedUpsert.ts
> +import { sliceIntoChunks } from "./util.ts";
The `sliceIntoChunks` function below was a duplicate of what we have in utils.

2023-12-20 19:16 UTC, austin-denoble commented on src/utils/chunkedUpsert.ts
> +          await index.namespace(namespace).upsert(chunk);
Previously we were upserting `vectors` instead of the chunk itself.

2023-12-20 23:51 UTC, rschwabco requested changes
Other than the hard coded region/cloud - lgtm

2024-01-16 06:34 UTC, austin-denoble commented
> Other than the hard coded region/cloud - lgtm

`PINECONE_CLOUD` and `PINECONE_REGION` have been added as env variables.

2024-01-16 06:35 UTC, merged